[package]
name = "Regexer"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.3", features = ["persistence"] }
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
